name: "Publish dist/*.whl file"

on:
  push:
    branches:
      - "main"
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish-to-pypi:
    name: "Publish to PyPI"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the main branch"
        uses: actions/checkout@main
      - name: "Publish /dist/* file to PyPI"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

  publish-to-releases:
    name: "Publish to repository Releases section"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the main branch"
        uses: actions/checkout@main
      - name: "Upload /dist/* file to Releases"
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /dist/*
          file_glob: true
          overwrite: true
          tag: ${{ github.ref }}
          body: "${{ github.ref }} distribution. Uploaded automatically with Actions."
