name: "Publish dist/*.whl file"

on:
  push:
    # Apparently every condition here uses logical OR so don't include branches
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  publish-to-pypi:
    name: "Publish to PyPI"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the main branch"
        uses: actions/checkout@main
      - name: "Publish /dist/* file to PyPI"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

  publish-to-releases:
    name: "Publish to repository Releases section"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the main branch"
        uses: actions/checkout@main
      - name: "Create Release"
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
      # Glob workaround from https://github.com/actions/upload-release-asset/issues/47#issuecomment-668543873
      - name: "Get name of artifact"
        run: |
          PATHNAME=$(ls dist/*.whl | head -n 1)
          NAME=$(basename $PATHNAME)
          echo ::set-env name=NAME::${NAME}
          echo ::set-env name=PATHNAME::${PATHNAME}
      - name: "Upload asset to Release"
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Access the upload_url output from the step with ID create_release
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.PATHNAME }}
          asset_name: ${{ env.NAME }}
          asset_content_type: application/x-wheel+zip
